apiVersion: v1
kind: Secret
metadata:
    name: dbpassword
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Q8thzH4Hbeo=,iv:Buj6YD4kbz34z5vsg+yJr5DraxXNY5bi3H3EVFiEtP4=,tag:xDLrXBJEy+miwJ7t7L5e4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17udw0v7x79qcj7jxj2yvxkgestj0233me0prk58vxgskppfldf6qugrye6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQkxhRXhUU3JiSHVJdFRr
            ZTF2eDJaVmFaejRVSkJkWHZBVUVwakVONkE0CjFlVlZhbEJrNXdvUmY5VEI1dW05
            bXViSjZ5S05WV1ZMMDZvUExLcmNiT0UKLS0tIHJnUENkQlFYV1pWZElQUmx3Mlll
            b3llN1dkcys3UlZvVDFSNGFCREhldmMKuQ4Kb+yCmsBMJyEr92nagUiydIBND+NU
            eWP6AgMWMv4DeakEvv2K7BgZpv7Z3XpKXhn4QV5hm7SY9a6XQH2OzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-28T16:53:06Z"
    mac: ENC[AES256_GCM,data:La5ZIWdQT1DjTh/clQ2GhbnFrL72m7d14exi3JPf1/bOiyGfwS4uMoH82j6F1nqdDt5i2aFg0eQHdE2D4NJlq52J50mtZAutWwhtatjxf7nHCdGS0zTCw5LxPpBkqB2AnIN5RIaSXJjJoLdS7p7s5723D+6KPxUAWLcZ5G3UQEA=,iv:2Btkt37Xg7TipRjLAo367qAAHcLwX3Chdq4y+us63Ew=,tag:7IFJF65blRbtx1m6hgpsIA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
